# Generated by Django 4.2.5 on 2023-12-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='attendance',
            field=models.CharField(max_length=20),
        ),
    ]
